on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        shell: bash

      - name: Fix permissions on target directory
        run: |
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.VPS_IP }} "sudo chown -R ubuntu:ubuntu /var/www/html/"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_IP }}
          REMOTE_USER: ubuntu
          TARGET: /var/www/html/